server:
  port: 9092

spring:
  application:
    name: gateway-service

zuul:
  routes:
    discovery:
      path: /v0/discovery/**
      url: http://localhost:8761
    apply-service:
      path: /v0/apply-service/**
      url: http://localhost:8081
