version: '3.8'
services:
  config-service:
    image: com.sfu.healthcare/enrollee-docker-config-service:v0
    ports:
      - 8088:8088
  discovery-service:
    image: com.sfu.healthcare/enrollee-docker-discovery-service:v0
    ports:
      - 8761:8761
  enrollee-service:
    image: com.sfu.healthcare/enrollee-docker-enrollee-service:v0
    ports:
      - 8081:8081
    depends_on:
      - discovery-service
      - config-service
  gateway-service:
    image: com.sfu.healthcare/enrollee-docker-gateway-service:v0
    ports:
      - 9092:9092
    depends_on:
      - discovery-service
      - config-service