server:
  port: 8088
spring:
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      server:
        native:
          search-locations: file:///anywhereYouReplace/app-config